#!/usr/bin/env python3
"""
Phase 1A: Generate data profile report (Markdown) and optionally validate relationships.
Usage: python scripts/generate_data_profile.py [--validate-joins] [--out docs/DATA_PROFILE_REPORT.md]
"""
from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent.parent
RAW_OLIST = PROJECT_ROOT / "raw" / "olist"
DEFAULT_OUT = PROJECT_ROOT / "docs" / "DATA_PROFILE_REPORT.md"

EXPECTED = [
    ("olist_orders_dataset.csv", "order_id", ["customer_id"], 99441),
    ("olist_order_items_dataset.csv", None, ["order_id", "product_id", "seller_id"], 112650),
    ("olist_order_payments_dataset.csv", None, ["order_id"], 103886),
    ("olist_order_reviews_dataset.csv", "review_id", ["order_id"], 99224),
    ("olist_products_dataset.csv", "product_id", [], 32951),
    ("olist_customers_dataset.csv", "customer_id", [], 99441),
    ("olist_sellers_dataset.csv", "seller_id", [], 3095),
    ("olist_geolocation_dataset.csv", None, ["geolocation_zip_code_prefix"], 1000462),
]


def format_size(path: Path) -> str:
    n = path.stat().st_size
    if n >= 1024 * 1024:
        return f"{n / (1024 * 1024):.2f} MB"
    return f"{n / 1024:.1f} KB"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT, help="Output Markdown file")
    ap.add_argument("--validate-joins", action="store_true", help="Check FK referential integrity")
    args = ap.parse_args()

    if not RAW_OLIST.exists():
        raise SystemExit(f"Not found: {RAW_OLIST}. Run download_olist.py first.")

    # Load all tables (light: only key columns for join validation)
    tables: dict[str, pd.DataFrame] = {}
    for f, pk, fks, _ in EXPECTED:
        path = RAW_OLIST / f
        if not path.exists():
            continue
        tables[f] = pd.read_csv(path)

    rows = []
    join_issues = []

    for f, pk, fks, exp_rows in EXPECTED:
        if f not in tables:
            rows.append((f, "MISSING", "—", pk or "—", ", ".join(fks) or "—", "—", "—"))
            continue
        df = tables[f]
        n = len(df)
        size = format_size(RAW_OLIST / f)
        null_pct = (df.isnull().sum() / n * 100)
        null_cols = null_pct[null_pct > 0]
        null_str = "; ".join(f"{c}: {v:.1f}%" for c, v in null_cols.items()) if len(null_cols) else "None"
        dup_str = "—"
        if pk and pk in df.columns:
            dup = df.duplicated(subset=[pk]).sum()
            dup_str = f"{dup} duplicates" if dup else "0"
        rows.append((f, f"{n:,}", size, pk or "—", ", ".join(fks) or "—", null_str, dup_str))

        if args.validate_joins and fks:
            for fk in fks:
                if fk not in df.columns:
                    continue
                # Resolve parent table and key
                if fk == "order_id":
                    parent_df = tables.get("olist_orders_dataset.csv")
                    parent_key = "order_id"
                elif fk == "customer_id":
                    parent_df = tables.get("olist_customers_dataset.csv")
                    parent_key = "customer_id"
                elif fk == "product_id":
                    parent_df = tables.get("olist_products_dataset.csv")
                    parent_key = "product_id"
                elif fk == "seller_id":
                    parent_df = tables.get("olist_sellers_dataset.csv")
                    parent_key = "seller_id"
                elif fk == "geolocation_zip_code_prefix":
                    parent_df = tables.get("olist_geolocation_dataset.csv")
                    parent_key = "geolocation_zip_code_prefix"
                else:
                    continue
                if parent_df is None:
                    continue
                parent_set = set(parent_df[parent_key].dropna().astype(str))
                child_set = set(df[fk].dropna().astype(str))
                orphan = child_set - parent_set
                if orphan:
                    join_issues.append((f, fk, len(orphan), "orphan FKs (no parent)"))
                missing = parent_set - child_set  # optional: parents with no child
                # We don't report missing as error (e.g. orders with no payment yet)

    # Build Markdown
    md = [
        "# Olist Brazilian E-Commerce – Data Profile Report",
        "",
        "Phase 1A – Generated by `scripts/generate_data_profile.py`",
        "",
        "## 1. Summary Table",
        "",
        "| Table | Row count | File size | Primary key | Foreign keys | Null % (columns) | Duplicates (PK) |",
        "|-------|----------|-----------|-------------|--------------|-------------------|------------------|",
    ]
    for r in rows:
        md.append(f"| {r[0]} | {r[1]} | {r[2]} | {r[3]} | {r[4]} | {r[5]} | {r[6]} |")

    md.extend([
        "",
        "## 2. Key Columns (PKs, FKs)",
        "",
        "| Table | Primary key | Foreign keys |",
        "|-------|-------------|--------------|",
    ])
    for f, _, _, pk, fks, _, _ in rows:
        md.append(f"| {f} | {pk} | {fks} |")

    md.extend([
        "",
        "## 3. Data Quality Observations",
        "",
        "- **Nulls**: See Summary Table; product_category_name and review comments often have nulls.",
        "- **Duplicates**: Primary keys should have 0 duplicates (orders.order_id, reviews.review_id, etc.).",
        "- **Referential integrity**: Run with `--validate-joins` to check orphan FKs.",
        "",
        "## 4. Relationships (Can Tables Join?)",
        "",
        "```",
        "customers (customer_id) 1 ──* orders (order_id)",
        "orders 1 ──* order_items, order_payments, order_reviews",
        "order_items *──1 products (product_id), sellers (seller_id)",
        "customers/sellers *──1 geolocation (geolocation_zip_code_prefix)",
        "```",
        "",
        "Expected: All FKs in order_items, order_payments, order_reviews reference orders.order_id; ",
        "order_items references products and sellers; customers/sellers reference geolocation.",
        "",
    ])

    if args.validate_joins and join_issues:
        md.extend([
            "## 5. Join Validation Results",
            "",
            "| Table | FK | Issue count | Note |",
            "|-------|-----|-------------|------|",
        ])
        for t, fk, cnt, note in join_issues:
            md.append(f"| {t} | {fk} | {cnt} | {note} |")
        md.append("")
    elif args.validate_joins:
        md.append("## 5. Join Validation Results\n\nNo orphan FKs found; tables can join as expected.\n")

    md.append("## 6. File Naming Convention\n")
    md.append("- **Folder**: `raw/olist/`")
    md.append("- **Pattern**: `olist_<table>_dataset.csv`")
    md.append("- Tables: orders, order_items, order_payments, order_reviews, products, customers, sellers, geolocation")

    out_path = args.out
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(md), encoding="utf-8")
    print("Wrote:", out_path)
    if join_issues:
        print("Join issues:", join_issues)


if __name__ == "__main__":
    main()
